name: Individuel - recette
services:
  # ==============================
  # ENV: RECETTE (8085)
  # ==============================
  web_recette:
    build: .
    container_name: meetrooms_web_recette
    ports:
      - "${PORT}:80"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db_recette

  db_recette:
    image: mariadb:10.11
    container_name: meetrooms_db_recette
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_recette_data:/var/lib/mysql
      - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  db_recette_data:
