name: Individuel - prod
services:
  # ==============================
  # ENV: PROD (8086)
  # ==============================
  web_prod:
    image: ${DOCKER_HUB_USER}/meetrooms-web:latest
    container_name: meetrooms_web_prod
    ports:
      - "${PORT}:80"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db_prod

  db_prod:
    image: mariadb:10.11
    container_name: meetrooms_db_prod
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_prod_data:/var/lib/mysql
      - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  db_prod_data:
